### List All Users
GET http://localhost:7456/worko/user
Authorization: Basic YWRtaW46cGFzc3dvcmQ=


### Create a New User
POST http://localhost:7456/worko/user
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
Content-Type: application/json

{
    "email": "mony@gmail.com",
    "name": "mony",
    "age": 25,
    "city": "Hyderabad",
    "zipCode": "10011"
}

